version: "3.9"

services:
  chat-api:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - devopsgpt-network

  chat-ui:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - chat-api
    networks:
      - devopsgpt-network

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - devopsgpt-network

networks:
  devopsgpt-network:
    driver: bridge